---
flavours:
  - architectures: [ 'amd64' ]
    platforms: [ metal ]
    modifiers: [ [ ghost, _prod ] , [ chost, _prod ] , [ vhost, _prod ] ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    modifiers: [ [] ]
    platforms: [ base ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ base ]
    modifiers: [ [ _build ] ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ metal ]
    modifiers: [ [] ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ aws, azure, gcp, ali, openstack, vmware, kvm ]
    modifiers: [ [ ghost, _prod ] , [ chost, _prod ] ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ aws, azure, gcp, ali, openstack, vmware, kvm ]
    modifiers: [ [] ]
    fails: [ unit, integration ]
  - architectures: [ 'amd64' ]
    platforms: [ gcp ]
    modifiers: [ [ chost, _prod ] ]
    fails: [ unit ]
