apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repo-task
  namespace: gardenlinux-tkn
spec:
  params:
    - name: 'giturl'
      type: 'string'
      default: 'ssh://git@github.com/gardenlinux/gardenlinux'
      description: 'git repository url'
    - name: 'committish'
      type: 'string'
      description: 'the committish to build'
      default: 'master'
    - name: 'repodir'
      description: 'relative path (below workspace) to put the repository worktree into'
      default: 'repo'
  workspaces:
    - name: ws
  steps:
    - name: 'retrieve-repository'
      image: 'eu.gcr.io/gardener-project/cc/job-image:1.612.0'
      script: |
        #!/usr/bin/env python3
        import os
        import urllib.parse
        import shutil

        import ccc.github
        import gitutil

        repo_dir = os.path.abspath(os.path.join('$(workspaces.ws.path)', '$(params.repodir)'))
        repo_url = urllib.parse.urlparse('$(params.giturl)')
        github_cfg = ccc.github.github_cfg_for_hostname(
          repo_url.hostname,
        )
        git_helper = gitutil.GitHelper.clone_into(
          target_directory=repo_dir,
          github_cfg=github_cfg,
          github_repo_path=repo_url.path,
        )
        git_helper.repo.git.checkout('$(params.committish)')

        print(f'cloned into {repo_dir} - checked out: $(params.committish)')
        print(git_helper.repo.git.show())
